import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import { Providers } from "@/store";
import { Toaster } from "sonner";
import ClientModals from "@/components/modals/ClientModals";
import GlobalLoaderProvider from "@/components/common/GlobalLoaderProvider";
import Header from "@/components/HomeComponents/Header";
import Footer from "@/components/HomeComponents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PostZest",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalLoaderProvider>
          <Providers>
            <ReactQueryProvider>
              <Header />
              {children}
              <Footer />
            </ReactQueryProvider>
            <Toaster
              position="top-right"
              toastOptions={{
                classNames: {
                  toast: "border-current/25 shadow-lg shadow-current/25",
                  success: "text-green-600 bg-green-50",
                  error: "text-red-600 bg-red-50",
                },
              }}
            />

            <ClientModals />
          </Providers>
        </GlobalLoaderProvider>
      </body>
    </html>
  );
}
